# Generated by Django 3.0.7 on 2020-06-29 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Ativo?'),
        ),
    ]
