# Generated by Django 3.0.7 on 2020-06-29 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='client',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.Client'),
        ),
    ]
