# Generated by Django 3.0.7 on 2020-07-04 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200704_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Client'),
        ),
    ]
